name: SonarQube Analysis
on:
  # Trigger analysis when pushing in master
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    # Dependabot actor does not have access to secrets so skill the analysis
    if: ${{ github.actor != 'dependabot[bot]' }}
    name: SonarQube Trigger
    runs-on: ubuntu-latest
    steps:
            
    - name: Checkout
      uses: actions/checkout@v4
    
    # Setup java 17
    - name: Setup Java JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 21
                  
    - name: SonarCloud Analysis
      env:
        SONAR_ORGANISATION: ${{ secrets.SONAR_ORGANISATION }}
        SONAR_LOGIN: ${{ secrets.SONAR_LOGIN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
      run:
        mvn --file pom.xml -B -Pcoverage -Dsonar.token=$SONAR_LOGIN -Dsonar.projectKey=com.mars-sim:mars-sim -Dsonar.organization=$SONAR_ORGANISATION verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
