name: SonarQube Analysis
on:
  # Trigger analysis when pushing in master 
  push:
    branches:
      - master
jobs:
  sonarqube:
    name: SonarQube Trigger
    runs-on: ubuntu-latest
    steps:
            
    - name: Checkout
      uses: actions/checkout@v3
    
    # Setup java 17
    - name: Setup Java JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 17

    - name: SonarCloud Analysis
      if: ${{ github.repository == 'mars-sim/mars-sim' }}
      env:
        SONAR_ORGANISATION: ${{ secrets.SONAR_ORGANISATION }}
        SONAR_LOGIN: ${{ secrets.SONAR_LOGIN }}
        SONAR_LABEL: ${{ github.workflow }}/${{ github.run_number }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
      run:
        mvn --file pom.xml -B -Pcoverage -Dsonar.token=$SONAR_LOGIN -Dsonar.organization=$SONAR_ORGANISATION -Dsonar.projectVersion="$SONAR_LABEL" verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
